//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714mswanson2h
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StreamingModelContainer : DbContext
    {
        public StreamingModelContainer()
            : base("name=StreamingModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Subscription> Subscriptions1 { get; set; }
        public virtual DbSet<Moderators> Moderators { get; set; }
        public virtual DbSet<Follows> Follows { get; set; }
        public virtual DbSet<Clips> Clips { get; set; }
        public virtual DbSet<Vods> Vods { get; set; }
    }
}
