//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1714mswanson2h
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vods
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vods()
        {
            this.Clips = new HashSet<Clips>();
        }
    
        public int Id { get; set; }
        public int TotalViews { get; set; }
        public bool SubOnly { get; set; }
        public System.TimeSpan VodLength { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Person Person { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Clips> Clips { get; set; }
    }
}
